#!/usr/bin/php
<?php

$loader = require 'vendor/autoload.php';

$config = parse_ini_file('slapper.conf');

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \Slapper\Console\Command\Send());
$application->run();
